### PR TITLE
don't block on stopping the perf map

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan PTAL

This will fix CI. Something has changed underneath...

**Comment by vrothberg** [comment]
I could also reproduce locally btw.

**Comment by vrothberg** [comment]
@giuseppe PTAL

**Comment by rhatdan** [comment]
Could this cause a race condition?

**Comment by vrothberg** [comment]
> Could this cause a race condition?

No as the tracer has stopped already (i.e., the BPF program signaled that it's done). I didn't invest too much time into analysing the root cause. We may need to close the module before but I don't have enough time. Something must have changed but I have no clue what. I assume something in the bcc lib.

**Pull request merged**
