### PR TITLE
Cirrus: Update CI VM Images

### PR DESCRIPTION
**Pull request by cevich**
Also update env. var. name for consistency with other repos.

### CODE REVIEW

**Comment by cevich** [comment]
@vrothberg PTAL.  I have no idea what "exit code 1" means :confused:

**Comment by vrothberg** [comment]
Added to my todo list :heavy_check_mark:

**Comment by vrothberg** [comment]
The fact that https://github.com/containers/oci-seccomp-bpf-hook/pull/110 still passes CI increases my fear that some dependency (bcc-devel?) has a fart on Fedora or maybe even the kernel.

**Comment by cevich** [comment]
> has a fart on Fedora or maybe even the kernel.

Wild-guess: I pressed the re-run button.

**Comment by vrothberg** [comment]
> @vrothberg is there a way to make the hook produce more verbose output? "Exit 1" isn't very useful in helping determining the cause of breakage.

I can look into it but it's probably hard as it runs in the background.  The errors can be found in the `journal` though.

**Comment by cevich** [comment]
Oh! So it would probably be a good idea to always collect the journal for the `build_and_test` task.  That's something I can arrange.

**Comment by cevich** [comment]
@vrothberg maybe this can sneak back onto your TODO list?

An alt. option: Disable CI on the repo. and/or deprecate the project.

**Comment by vrothberg** [comment]
It's shipped in RHEL, so we cannot eliminate it entirely but entire BPF stack seems rather fragile and it's not high on the team's priority list.

I finally managed to get a better error message which points to a kernel fart in Fedora as suspected.

```
oci-seccomp-bpf-hook (main) $ make binary && sudo ./bin/oci-seccomp-bpf-hook -r 187657 -o /tmp/test.log                                                     
GO111MODULE=on go build -mod=vendor -mod=vendor -o bin/oci-seccomp-bpf-hook -ldflags "-X main.version=v1.2.9-dev" github.com/containers/oci-seccomp-bpf-hook
INFO[0000] Running floating process PID to attach: 187657                                                                                                   
In file included from /virtual/main.c:2:                                                                                                                    
include/linux/bpf.h:303:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_list_head'                                             
                return sizeof(struct bpf_list_head);                                                                                                        
                       ^     ~~~~~~~~~~~~~~~~~~~~~~                                                                                                         
include/linux/bpf.h:303:24: note: forward declaration of 'struct bpf_list_head'                                                                             
                return sizeof(struct bpf_list_head);                                                                                                        
                                     ^                                                                                                                      
include/linux/bpf.h:305:10: error: invalid application of 'sizeof' to an incomplete type 'struct bpf_list_node'                                             
                return sizeof(struct bpf_list_node);                                                                                                        
                       ^     ~~~~~~~~~~~~~~~~~~~~~~                                                                                                         
include/linux/bpf.h:305:24: note: forward declaration of 'struct bpf_list_node'                                                                             
                return sizeof(struct bpf_list_node);                                                                                                        
                                     ^                                                                                                                      
include/linux/bpf.h:323:10: error: invalid application of '__alignof' to an incomplete type 'struct bpf_list_head'                                          
                return __alignof__(struct bpf_list_head);                                                                                                   
                       ^          ~~~~~~~~~~~~~~~~~~~~~~                                                                                                    
include/linux/bpf.h:323:29: note: forward declaration of 'struct bpf_list_head'                                                                             
                return __alignof__(struct bpf_list_head);                                                                                                   
                                          ^                                                                                                                 
include/linux/bpf.h:325:10: error: invalid application of '__alignof' to an incomplete type 'struct bpf_list_node'                                          
                return __alignof__(struct bpf_list_node);                                                                                                   
                       ^          ~~~~~~~~~~~~~~~~~~~~~~                                                                                                    
include/linux/bpf.h:325:29: note: forward declaration of 'struct bpf_list_node'                                                                             
                return __alignof__(struct bpf_list_node);                                                                                                   
                                          ^                                                                                                                 
include/linux/bpf.h:1980:30: error: field has incomplete type 'enum bpf_cgroup_iter_order'                                                                  
                enum bpf_cgroup_iter_order order;                                                                                                           
                                           ^                                                                                                                
include/linux/bpf.h:1980:8: note: forward declaration of 'enum bpf_cgroup_iter_order'                                                                       
                enum bpf_cgroup_iter_order order;                                                                                                           
                     ^                                                                                                                                      
5 errors generated.                                                                                                                                         
INFO[0001] Loading enter tracepoint                                                                                                                         
panic: runtime error: invalid memory address or nil pointer dereference                                                                                     
        panic: runtime error: invalid memory address or nil pointer dereference                                                                             
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5338d4]                                                                                      
                                                                                                                                                            
goroutine 1 [running]:                                                                                                                                      
github.com/iovisor/gobpf/bcc.(*Module).Close.func1(0x4be443?)                                                                                               
        /home/vrothberg/containers/oci-seccomp-bpf-hook/vendor/github.com/iovisor/gobpf/bcc/module.go:155 +0x14                                             
github.com/iovisor/gobpf/bcc.(*Module).Close(0x0)                                                                                                           
        /home/vrothberg/containers/oci-seccomp-bpf-hook/vendor/github.com/iovisor/gobpf/bcc/module.go:155 +0x36                                             
panic({0x55c100, 0x681f00})                                                                                                                                 
        /usr/lib/golang/src/runtime/panic.go:890 +0x263                                                                                                     
github.com/iovisor/gobpf/bcc.(*Module).Load(0x0, {0x58242f, 0xb}, 0x1?, 0x1?, 0x6?)                                                                         
        /home/vrothberg/containers/oci-seccomp-bpf-hook/vendor/github.com/iovisor/gobpf/bcc/module.go:225 +0x36                                             
github.com/iovisor/gobpf/bcc.(*Module).LoadTracepoint(...)                                                                                                  
        /home/vrothberg/containers/oci-seccomp-bpf-hook/vendor/github.com/iovisor/gobpf/bcc/module.go:205                                                   
main.runBPFSource(0xc000078180?, {0x7ffe6647a714, 0xd}, {0x0, 0x0})                                                                                         
        /home/vrothberg/containers/oci-seccomp-bpf-hook/oci-seccomp-bpf-hook.go:226 +0x3a9                                                                  
main.main()                                                                                                                                                 
        /home/vrothberg/containers/oci-seccomp-bpf-hook/oci-seccomp-bpf-hook.go:84 +0x3be                                                                   
```

**Comment by cevich** [comment]
> It's shipped in RHEL

oh geeze, I didn't realize that.

> the entire BPF stack seems rather fragile

Yeah, like they change it with every major kernel update.  Though, I guess that's somewhat not too surprising.

Hmmm.

I've got rawhide-images on my radar for podman CI, perhaps they would be of use here as well?  I'm thinking in addition to the current test, basically to help spot these kinds of problems earlier rather than later.

**Comment by vrothberg** [comment]
> I've got rawhide-images on my radar for podman CI, perhaps they would be of use here as well? 

I think that would help track down things, thanks!  At least the locality of time may help identify what broke.

**Review by vrothberg — APPROVED** [review]
LGTM
Thanks for your patience, @cevich !

**Pull request merged**
