### PR TITLE
Cirrus: Update CI VM images to F37

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by vrothberg** [comment]
> make validate
./build/golangci-lint run
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

**Comment by cevich** [comment]
Yeah, that one.  What's it mean?

**Comment by vrothberg** [comment]
> Yeah, that one. What's it mean?

I can reproduce locally.  We need a newer golangci-lint. I'll prepare a fix.

**Comment by cevich** [comment]
ugh, no matter how hard I hammer on it, git refuses to apply that patch.

**Comment by vrothberg** [comment]
> ugh, no matter how hard I hammer on it, git refuses to apply that patch.

Copy everything verbatim into $file and do a `git am $file`.

**Comment by cevich** [comment]
aye, that's what I did.  git said "NO!".  I'll just manually copy/paste the changes...

**Comment by cevich** [comment]
@vrothberg tests are green.  PTAL when you have a chance.  Thanks.

**Comment by rhatdan** [comment]
LGTM

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
Thank you, @cevich !

**Pull request merged**
