### PR TITLE
Update VM image to F34beta + use shared hack/get_ci_vm.sh

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by vrothberg** [comment]
```
not ok 4 Trace and use generated profile
# (in test file test/00-simple.bats, line 60)
#   `[ "${size}" -gt 0 ]' failed
# Temporary file: /tmp/tmp.Q4b4t596sP
# Podman output: bin dev etc home lib media mnt opt proc root run sbin srv sys tmp usr var
# Size of generated file: 0
not ok 5 Containers fails to run blocked syscall
# (in test file test/00-simple.bats, line 82)
#   `[ "${size}" -gt 0 ]' failed
# Temporary file: /tmp/tmp.kavtlcEZTu
# Podman output: bin dev etc home lib media mnt opt proc root run sbin srv sys tmp usr var
# Size of generated file: 0
not ok 6 Extend existing seccomp profile
# (in test file test/00-simple.bats, line 104)
#   `[ "$status" -eq 0 ]' failed with status 126
# Temporary file 1: /tmp/tmp.NLnKTjBv37
# Temporary file 2: /tmp/tmp.pam3j8EOiS
not ok 7 Syscall blocked in input profile remains blocked in output profile
# (in test file test/00-simple.bats, line 143)
#   `[ "$status" -eq 0 ]' failed with status 126
# Temporary file : /tmp/tmp.aLjRkC4hrh
# Podman output: Error: OCI runtime error: error executing hook `/usr/libexec/oci/hooks.d/oci-seccomp-bpf-hook` (exit code: 1)
not ok 8 Trace and look for syslogs
# (in test file test/01-syslog.bats, line 16)
#   `[ "$status" -eq 0 ]' failed with status 126
# Temporary file: /tmp/tmp.EgsVzw2fFZ
# Podman output: Error: OCI runtime error: error executing hook `/usr/libexec/oci/hooks.d/oci-seccomp-bpf-hook` (exit code: 1)
make: *** [Makefile:66: test-integration] Error 1
```

I have absolutely no time to look into this at the moment :(

**Comment by vrothberg** [comment]
Thanks, @cevich!

>  Size of generated file: 0

@giuseppe, could this be crun?  We had a similar symptom earlier this year/late last year when crun nuked the hooks.

**Comment by giuseppe** [comment]
locally I am seeing the `oci-seccomp-bpf` never terminates and ends up in a loop.

Could be caused by a newer kernel

**Comment by giuseppe** [comment]
from some quick debugging I see there are a lot of perf events lost, including the `stopTracing` one.  We can probably easily workaround it by storing the termination status and once set, let `enter_trace` always return it, but don't we risk to lose syscalls for the same reason?

**Comment by vrothberg** [comment]
> from some quick debugging I see there are a lot of perf events lost, including the `stopTracing` one. We can probably easily workaround it by storing the termination status and once set, let `enter_trace` always return it, but don't we risk to lose syscalls for the same reason?

Thanks for checking.  Loosing perf events sounds concerning.  Do you know a trick how we could buffer them?

**Comment by giuseppe** [comment]
one thing I'd investigate is the usage of `BPF_RINGBUF_OUTPUT` instead of `BPF_PERF_OUTPUT` and specify a bigger buffer size.
Another possibility is to handle the events inside the eBPF code itself (store the used syscalls to a map), then pass the information to the handler at shutdown time, it could probably just read the map of syscalls.
Do we care about the arguments to the syscalls?

**Comment by vrothberg** [comment]
Great idea!

We don't care about the syscall args.

**Comment by giuseppe** [comment]
> Great idea!
> 
> We don't care about the syscall args.

opened a PR: https://github.com/containers/oci-seccomp-bpf-hook/pull/77

not exactly what I was thinking of in the previous comment, but it helps to reduce the amount of perf events and cap them to the number of used syscalls

**Comment by rhatdan** [comment]
#77 is merged.

**Comment by giuseppe** [comment]
@cevich could you try to rebase and we see what happens?

**Comment by giuseppe** [comment]
@cevich are you fine with https://github.com/containers/oci-seccomp-bpf-hook/pull/79?

**Comment by rhatdan** [comment]
I merged @giuseppe version, Please update if his needs additional changes.

**Pull request closed without merging**
