### PR TITLE
enable Travis CI

### PR DESCRIPTION
**Pull request by vrothberg**
Minimal checks and some infra-code from libpod.  We want to migrate to
Cirrus CI soon but we can start with Travis first.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Don't merge yet. I want to add bats test on top of this PR. Just opened early to see if the initial commit gets green.

**Comment by vrothberg** [comment]
I can't believe it. It's green. Will play with bats tests now.

**Comment by vrothberg** [comment]
@rhatdan PTAL. CI is up an running now. We're using the atomic ppa to run Podman in Travis.

**Comment by rhatdan** [comment]
Awesome job @vrothberg LGTM

**Pull request merged**
