### PR TITLE
bump github.com/iovisor/gobpf to v0.1.1

### PR DESCRIPTION
**Pull request by lsm5**
This fixes a build issue on armv7hl

Signed-off-by: Lokesh Mandvekar <lsm5@fedoraproject.org>

@vrothberg @rhatdan PTAL

### CODE REVIEW

**Comment by lsm5** [comment]
related upstream fix: https://github.com/iovisor/gobpf/pull/274

**Comment by lsm5** [comment]
CI is acting weird. `make binary` worked just fine for me on f34 with golang 1.16. Is it a `new golang` issue perhaps?

@cevich the meta test has the $GCPJSON issue we saw somewhere else earlier. Any idea whatsup?

**Comment by vrothberg** [comment]
Restarted the test job

**Comment by lsm5** [comment]
still failing the same way :(

**Comment by lsm5** [comment]
@vrothberg 
1. Do you think the failures could go away with an older golang perhaps? 
2. Is a `vendor-in-container` Makefile target desirable like in podman?
3. Would you mind me giving me enough access to re-run CI tests?

**Comment by lsm5** [comment]
seems like some files in gobpf/pkg/ weren't added to the tree. Should work now (hopefully).

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by lsm5** [comment]
@vrothberg could you please cut a new release including this commit?

**Pull request merged**
