### PR TITLE
Switch to using syslog to make debugging easier

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
@rhatdan, maybe we can get https://github.com/containers/oci-seccomp-bpf-hook/pull/8 merged first and add a bats test for logging?

**Comment by rhatdan** [comment]
@vrothberg The validate lint is not working well for me?

**Comment by vrothberg** [comment]
It's the vendoring check that fails: https://travis-ci.org/containers/oci-seccomp-bpf-hook/builds/588046197#L358

Can you rerun `make vendor` and add the changed files?

**Comment by rhatdan** [comment]
When I run `make vendor` locally I see no change.

**Comment by vrothberg** [comment]
Eeek. Looks like the Travis go gets crazy. We had that this week already.

We could try setting the go version in `.travis.yml`:
```yaml
go:
  - 1.12.x
```
Or even 1.13.x if it's already avaiable.

**Pull request merged**
